home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: []
login:
  uri: /login
  controller: SecurityController
  action: login
  parameters: []
contact:
  uri: /contact
  controller: IndexController
  action: contact
  parameters: []
register:
  uri: /register
  controller: SecurityController
  action: register
  parameters: []
post:
  uri: /blog/([a-zA-Z-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["slug"]
posts:
  uri: /blog
  controller: BlogController
  action: listPosts
  parameters: []
create:
  uri: /admin/blog/create
  controller: BlogController
  action: createPost
  parameters: []
update:
  uri: /admin/blog/update/([a-zA-Z-9-]+)
  controller: BlogController
  action: updatePost
  parameters: ["slug"]
delete:
  uri: /admin/blog/delete/([a-zA-Z-9-]+)
  controller: BlogController
  action: deletePost
  parameters: ["slug"]