home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: []
admin:
  uri: /admin
  controller: AdminController
  action: index
  parameters: []
managePosts:
  uri: /admin/posts
  controller: AdminController
  action: managePosts
  parameters: []
manageComments:
  uri: /admin/comments
  controller: AdminController
  action: manageComments
  parameters: []
activateComment:
  uri: /admin/comments/activateComment
  controller: AdminController
  action: activateComment
  parameters: ["id"]
login:
  uri: /login
  controller: SecurityController
  action: login
  parameters: []
logout:
  uri: /logout
  controller: SecurityController
  action: logout
  parameters: []
contact:
  uri: /contact
  controller: IndexController
  action: contact
  parameters: []
register:
  uri: /register
  controller: SecurityController
  action: register
  parameters: []
post:
  uri: /blog/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["slug"]
posts:
  uri: /blog
  controller: BlogController
  action: listPosts
  parameters: []
create:
  uri: /admin/blog/create
  controller: BlogController
  action: createPost
  parameters: []
update:
  uri: /admin/blog/update/([a-zA-Z0-9-]+)
  controller: BlogController
  action: updatePost
  parameters: ["slug"]
delete:
  uri: /admin/blog/delete/([a-zA-Z0-9-]+)
  controller: BlogController
  action: deletePost
  parameters: ["slug"]