home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: []
admin:
  uri: /admin
  controller: AdminController
  action: index
  parameters: []
updateAdminInfos:
  uri: /admin/profile/update/([0-9]+)
  controller: AdminController
  action: updateAdminInfos
  parameters: ["id"]
updateAdminFiles:
  uri: /admin/profile/updateFiles/([0-9]+)
  controller: AdminController
  action: updateAdminFiles
  parameters: ["id"]
managePosts:
  uri: /admin/posts
  controller: AdminController
  action: managePosts
  parameters: []
manageComments:
  uri: /admin/comments
  controller: AdminController
  action: manageComments
  parameters: []
manageSocials:
  uri: /admin/socials
  controller: AdminController
  action: manageSocials
  parameters: []
createSocial:
  uri: /admin/socials/create
  controller: AdminController
  action: adminCreateSocial
  parameters: []
deleteSocial:
  uri: /admin/socials/delete/([0-9]+)
  controller: AdminController
  action: adminDeleteSocial
  parameters: ["id"]
updateSocial:
  uri: /admin/socials/update/([0-9]+)
  controller: AdminController
  action: adminUpdateSocial
  parameters: ["id"]
login:
  uri: /login
  controller: SecurityController
  action: login
  parameters: []
logout:
  uri: /logout
  controller: SecurityController
  action: logout
  parameters: []
contact:
  uri: /contact
  controller: IndexController
  action: contact
  parameters: []
register:
  uri: /register
  controller: SecurityController
  action: register
  parameters: []
post:
  uri: /blog/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["slug"]
posts:
  uri: /blog
  controller: BlogController
  action: listPosts
  parameters: []
create:
  uri: /admin/posts/create
  controller: BlogController
  action: createPost
  parameters: []
update:
  uri: /admin/posts/update/([a-zA-Z0-9-]+)
  controller: BlogController
  action: updatePost
  parameters: ["slug"]
delete:
  uri: /admin/blog/delete/([a-zA-Z0-9-]+)
  controller: BlogController
  action: deletePost
  parameters: ["slug"]
switchStatus:
  uri: /admin/switchStatus/([0-9]+)
  controller: AdminController
  action: switchStatus
  parameters: ["id"]
adminDeleteComment:
  uri: /admin/delete/([0-9]+)
  controller: AdminController
  action: adminDeleteComment
  parameters: ["id"]
